### ISSUE TITLE
Error: The requested key, section or file was not found.

### ISSUE THREAD

**Issue by ftlvz5** [KhryDL/Vroom-vroomMachine#2]
At the start of MD where you pick an EGO gift I get the following error:
```
Error: The requested key, section or file was not found.

▶	390: a := StrSplit(IniRead(A_ScriptDir "\Data\gifts.ini", A_Index), "=")

Call stack:
*MAIN.AHK (390) : [IniRead] a := StrSplit(IniRead(A_ScriptDir "\Data\gifts.ini", A_Index), "=")
*MAIN.AHK (390) : [selectGift] a := StrSplit(IniRead(A_ScriptDir "\Data\gifts.ini", A_Index), "=")
*MAIN.AHK (123) : [<Hotkey>] selectGift()
> +s
```
I've tried with the release version and the latest from main (compiling myself)

![image](https://user-images.githubusercontent.com/128587928/227365452-5fd8471c-1ae9-4a8c-ad67-1370e1a6acd0.png)

I'm not familiar with AHK scripting, first glance I don't see an issue in the script itself that may cause this and the Data directory is at the right location with the gifts.ini
![image](https://user-images.githubusercontent.com/128587928/227366301-379fe40c-6c59-4682-829c-6bc7172264de.png)

I'm using AHK v2, which should be the right version from what I've seen in the script.

**Comment by KhryDL** [comment]
i'm aware of this bug, sometimes the script can't recognize the ego gifts on screen, it should be fixed in the next version which i will hopefully release tomorrow
