### ISSUE TITLE
v0.3.2 Bug fail node detection

### ISSUE THREAD

**Issue by ftlvz5** [KhryDL/Vroom-vroomMachine#4]
for v0.3.2 still some problem with map detection, came out of abno event and failed to detect the elite node on the left from this screen position. reloading still same problem.

![dFCI4B4jAU](https://user-images.githubusercontent.com/128587928/227674575-bf77ce70-e67d-4198-989b-47b7dcf9644b.png)
![LimbusCompany_13gplfAqkQ](https://user-images.githubusercontent.com/128587928/227674587-9c4c5d41-acdf-4ee5-b50a-06fe9e823dd1.png)

**Comment by ftlvz5** [comment]
moving screen position around doesn't seem to help. zooming out and reloading fixes

**Comment by ftlvz5** [comment]
Trying to detect boss node too early
![dFCI4B4jAU](https://user-images.githubusercontent.com/128587928/227679174-46ebcba0-85b3-4d40-a153-e9c3b2649f8d.png)

**Comment by KhryDL** [comment]
The second bug should be fixed in the next version, as for the first one do you recall which abnormality was in the node?

**Comment by ftlvz5** [comment]
> The second bug should be fixed in the next version, as for the first one do you recall which abnormality was in the node?

It was the blue frog/melty eyeball abno. I saw it wasn't added yet so I've put screenshots of it in the gdrive.
So I manually completed the event and once back in the map I reloaded the script.

**Comment by KhryDL** [comment]
Oh i see, the script automatically zooms out if it presses a continue button (like at the end of the abnormality event)
The next time restart the script when the continue button is on the screen at the end of the event
