### ISSUE TITLE
v0.3.2 Late-bloomer's Tattoo/eyeMonster not detected

### ISSUE THREAD

**Issue by ftlvz5** [KhryDL/Vroom-vroomMachine#5]
![1_initial](https://user-images.githubusercontent.com/128587928/227676560-f815777b-d9fc-459a-a123-79a32e1a6fb7.png)
The above image is the initial text of Late-bloomer's Tatto/eyeMonster abno event. 

I see in /abnos/eyeMonster the image of "Heaven" text is used, which is referenced as Late Tattoo/tattoo.png on gdrive.
![eyeMonster](https://user-images.githubusercontent.com/128587928/227677844-540ca759-c79e-4be6-8d5d-e470f0ffea55.png)

"Heaven" text appears as second part for me after I've pressed skip on initial part. Possibility of 2 different initial text perhaps?
![2_options](https://user-images.githubusercontent.com/128587928/227678031-ae24f88a-6487-4394-a400-8a1043c9de50.png)

Suggested to use "cluster of eyes" (too if 2 initial cases are a thing), I'll upload the initial image as "cluster_of_eyes" to the gdrive under /Late Tattoo for your use.

**Comment by ftlvz5** [comment]
Looking closely at the existing tattoo.png with "Heaven" on gdrive, it is indeed also an initial text because on the right there's no options yet, so need both images to detect this event consistently.

**Comment by KhryDL** [comment]
Will add both in next version
