### ISSUE TITLE
v0.3.2 Not selecting correct ID: Faust - The One Who Grips

### ISSUE THREAD

**Issue by ftlvz5** [KhryDL/Vroom-vroomMachine#6]
When recruiting faust, the script doesn't select The One Who Grips which has been set, continues with default ID.

![image](https://user-images.githubusercontent.com/128587928/227719479-fda84be8-db6e-4e46-a9be-329e61c91a83.png)

video:
https://user-images.githubusercontent.com/128587928/227719502-18e31e6b-bd45-4494-9669-e23a9a2c1fd5.mp4

**Comment by ftlvz5** [comment]
It might be the position of the cursor that causes the problem because after selecting Faust, it is on The One Who Grips immediately which highlights it and that may make it unrecognizable.
![image](https://user-images.githubusercontent.com/128587928/227719724-e9e7ca1c-f624-4369-b056-50a6b9cbca56.png)
![image](https://user-images.githubusercontent.com/128587928/227719732-18ad7e0b-028a-465a-bb22-ce0fcc967572.png)

**Comment by ftlvz5** [comment]
If that is the cause, then adding an extra step between selecting the sinner and the ID can make it more reliable.
Like moving the cursor somewhere to the side so the all the ID text can be properly detected without any changes in pixel colors cause of the highlight by the hovering cursor.

**Comment by ftlvz5** [comment]
commit ec5cd226e7f1932c27eee026232eeb50fa38d694 fixed it.

https://user-images.githubusercontent.com/128587928/227729948-f5ac3735-776d-4ee3-b1ac-334bfe9d6065.mp4

**Comment by KhryDL** [comment]
That was indeed the issue, i was going to release a new version today with that and other fixes but i might delay it to tomorrow as i'm testing a new feature
