### ISSUE TITLE
Talisman Abno Event: Second case not added yet

### ISSUE THREAD

**Issue by ftlvz5** [KhryDL/Vroom-vroomMachine#7]
Currently talisman image looks for "Are the talismans"
Doesn't detect second case (added screenshot to gdrive /talisman/second case/):
![1_wooden_doll](https://user-images.githubusercontent.com/128587928/227721663-c99bc10f-a6e2-4e7d-8fe4-a5aac8cc314a.png)

**Comment by KhryDL** [comment]
from the screenshots it seems like the other user made a mistake, this is the right text

**Comment by ftlvz5** [comment]
> from the screenshots it seems like the other user made a mistake, this is the right text

I've encountered the talisman abno again with the second case I've mentioned previously which the script doesn't detect currently. so I do think there's two different cases the script needs to account for.
![talisman2](https://user-images.githubusercontent.com/128587928/227732536-555dc2b6-e185-4be4-a746-9255a55945c4.png)

**Comment by ftlvz5** [comment]
Or is it actually just one case? "Are the talismans" which is the current text it looks for appears when I've clicked skip once, so not from the start 
https://user-images.githubusercontent.com/128587928/227732822-f8fd738c-e93d-4ad0-91bb-2f577bc2503e.mp4

**Comment by KhryDL** [comment]
maybe i didn't make myself clear, if you look at this image https://drive.google.com/drive/folders/1wmHgVB7j-FoH_cLCh9uXcUY3701NsE9x you can see the text you posted on the top part of the abnormality box, the other user probably clicked on the screen by accident, there is only one case to account for, yours

If you or anyone encounters the "Are the talismans" text as the first one i will put both cases in the script

**Comment by ftlvz5** [comment]
I think we're both misunderstanding each other a bit, no problem.
Your link sends me to the root of the talisman folder.
To which image are you referring to? If you're referring to talisman 1.png in the root (other user's image) with "Are the talismans" as the top text. Then I agree too that the other user may have clicked once by accident.

The images I've uploaded are under the subfolder "second case". I initially thought there were 2 cases which turns out to be only 1 if our assumption holds true that it was an accident.

What I wanted to say is that the script is still using the other user's "Are the talismans" image (/Abnos/talismans.png), which is not the actual top text from my encounters of the abno event (seen in my screenshot and video).
![image](https://user-images.githubusercontent.com/128587928/227736089-f25fb4b2-b423-4d82-81ad-fa2a2a81bfd5.png)

So that's the reason the script still can't recognize the abno for me, and should be changed to an image of the text on my image.
![image](https://user-images.githubusercontent.com/128587928/227736395-177dad48-99e4-42c1-8310-323233ae79ae.png)

**Comment by ftlvz5** [comment]
> ... there is only one case to account for, yours
Like you've said. Since the issue got closed before, I thought the image with "Are the talismans" changed to a new one based of my image. 
Later on I've encountered the abno being unrecognizable again. Therefore I bring this issue up again.
