### ISSUE TITLE
Floor 2 bug: Searching for elite, instead switches to floor 3 and finds final boss (second bug)

### ISSUE THREAD

**Issue by ftlvz5** [KhryDL/Vroom-vroomMachine#8]
Testing on commit ec5cd226e7f1932c27eee026232eeb50fa38d694
Bug 1: Generally having trouble finding elite node on floor 2.
In this particular case I tried repositioning camera manually by panning to the left.
Bug 2: It ended up switch floor 2 -> 3 and detecting the abno node as the final boss node

Video:
https://streamable.com/as59qj

**Comment by KhryDL** [comment]
do you have a screenshot of when the message first appeared? i can't do anything otherwise

**Comment by ftlvz5** [comment]
Screenshot:
![floor2_elite_abno_boss_bug](https://user-images.githubusercontent.com/128587928/227735324-2486e629-72f8-4f4e-a05a-d728865a045d.png)

And did some further testing, tried to set it to floor 1.
it clicks on abno, which is normal behavior, but it increases floor to 2 which shouldn't happen.
then acts as if it were at floor 2, it clicks on abno again, floor increases to 3.
as if it's on floor 3, it detects abno as the final boss
Video:
https://user-images.githubusercontent.com/128587928/227735438-b0d2c518-d6a9-4287-9345-f8f894415486.mp4

**Comment by KhryDL** [comment]
should be fixed as of 497d3dffb222b3d1be296396fa2abb496c128fa6 , f79eb5fea686d60bd4cd9d91eb7fd3b47b372c8d should further lessen the issue

**Comment by ftlvz5** [comment]
on f1303cc836d581d845a4563e269c4c7ee11b3ff5
floor 2, failed to detect boss node
![map_node_bug_2303261755](https://user-images.githubusercontent.com/128587928/227788182-36c3200b-3f1a-4491-ac5e-c6baab3ce101.png)
![map_node_bug_full_2303261755](https://user-images.githubusercontent.com/128587928/227788186-7a61c722-682e-41e5-b3b0-313b1b489472.png)

**Comment by KhryDL** [comment]
fixed on f59b5fdd1047324896877d34c37b4a247bbc7c71
